name: Publish Lykke.Messaging.RabbitMq
on:
  push:
    tags: 
      - '*'
    paths:
      - src/Lykke.Messaging.RabbitMq/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Create the package
      run: dotnet pack --include-symbols --include-source --configuration Release src/Lykke.Messaging.RabbitMq/Lykke.Messaging.RabbitMq.csproj /p:Version=${GITHUB_REF#refs/tags/}
    - name: Publish the package to Nuget
      run: dotnet nuget push src/Lykke.Messaging.RabbitMq/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate
